name: Daily Repository Update

on:
  schedule:
    - cron: "0 2 * * *"  # Runs daily at 02:00 UTC
  workflow_dispatch:  # Allow manual triggers

jobs:
  daily-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git user (22f3000814@ds.study.iitm.ac.in)
        run: |
          git config --local user.email "22f3000814@ds.study.iitm.ac.in"
          git config --local user.name "github-actions[Ay]"

      - name: Create daily commit
        run: |
          echo "Daily update: $(date -u)" >> daily_update.log
          git add daily_update.log
          git commit -m "Automated daily update [skip ci]" || exit 0
          git push
